### ISSUE TITLE
Error to decrypt using the same information used on tests

### ISSUE THREAD

**Issue by oliveiramiguel** [rajatkumar/visa_msg_decrypt#2]
I'm having an error to decrypt and I'm using the same information (encKey, encPaymentData) that you used on tests.

I'm using node v7.0.0.

Error output:

```
HMAC:ck/TCCMSU6/lZPck0mXbpXmdaY/cNqaXz+xqx92Debo=
Generated HMAC:ck/TCCMSU6/lZPck0mXbpXmdaY/cNqaXz+xqx92Debo=
HMAC verification successfull
HMAC:1NtqYYWxaeUuP/yR4rzs3e1plLD0IhTkDkMXyfjnmLE=
Generated HMAC:D4b/+ncwhRPT5fErVG75+1fkfKMH7cs1ApZ0XipA2hg=
/node_modules/visa_msg_decrypt/js/index.js:73
        throw new Error('Invalid payload or key. HMAC verification failed.');
        ^

Error: Invalid payload or key. HMAC verification failed.
    at VisaPayloadDecrypt._decryptData (/node_modules/visa_msg_decrypt/js/index.js:73:15)
    at VisaPayloadDecrypt.decrypt (/node_modules/visa_msg_decrypt/js/index.js:40:30)
    at Object.<anonymous> (/visa.js:14:25)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
```

**Comment by aspinella** [comment]
Same error here =(
I'm using node 8.6
What versions of nodejs does it support?

**Comment by macarena** [comment]
Same here!
Wondering if the payload expected is the same i'm doing.
I'm using the object returned by Visa as it is.
`
V.on("payment.success", payment => {...});
`
then payload inputed on Decrypt.decrypt() method is the payment returned on the code above.
Am I doing it right???
